version: 2
updates:
    - package-ecosystem: github-actions
      directory: /
      schedule:
          interval: daily
      open-pull-requests-limit: 20
      groups:
          github-actions:
              applies-to: version-updates
              update-types:
                  - minor
                  - patch

    - package-ecosystem: npm
      directory: /
      schedule:
          interval: daily
      open-pull-requests-limit: 20
      groups:
          npm-packages:
              applies-to: version-updates
              update-types:
                  - minor
                  - patch
